"""Named constants used across the Palomero codebase."""

TILE_SIZE: int = 1024
DEFAULT_GRID_SIZE: float = 60.0
DEFAULT_SAMPLE_REGION_SIZE: float = 300.0
DEFAULT_SAMPLE_PIXELS: int = 4000
MAX_SAMPLE_PIXELS: int = 10000
DEFAULT_NUMBER_OF_ITERATIONS: int = 1000
ELLIPSE_NUM_POINTS: int = 100
MAX_TASK_RUNTIME_SECONDS: int = 600
DEFAULT_PIXEL_SIZE: float = 1.0
NAME_TRUNCATION_LENGTH: int = 23
PERCENTILE_RANGE: tuple[float, float] = (0.1, 99.9)
